---
title: "SCI"
output: html_document
date: "2024-03-13"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
require("tidyverse")
require("here")
require("readr")
library("plyr")
require("dplyr")
require("ggplot2")
require("lme4")
library(data.table)
library(rstatix)
library(emmeans)
require("performance")
require("insight")
require("magrittr")
library(see)
library(modelbased)
library("jtools")
require("kableExtra")
require("huxtable")
library(ggbeeswarm)
library("ggpubr")
library(reshape2)
require("WRS2")
library("ggExtra")
library("car")
library("readxl")


```
#demo data


```{r Demo, echo=FALSE, message=FALSE, warning=FALSE}

prop.test(x=18, n=22, p = c(0.50), correct = FALSE)


prop.test(x=c((12 * .916),(10 * .7)),n=c(12,10 )) 

```

## SF_36_SCI

```{r SF_36_SCI, echo=FALSE, message=FALSE, warning=FALSE}

RAND <- read_excel("SF_36.xlsx")
#view(RAND)
RAND <- RAND[c(1:11)]



pre  <- subset(RAND, PrePost %like% "1")
post <- subset(RAND, PrePost %like% "2")

p1 <- pre %>% filter(Group %like% "1")
tableC <-get_summary_stats(p1, show = c("min", "max","median", "iqr", "mean", "sd"))

SF36df <- full_join(pre, post, by = "ID")
SF36df$Phys      <- SF36df$Physical.y - SF36df$Physical.x
SF36df$PhysRole  <- SF36df$Role_Physical.y - SF36df$Role_Physical.x
SF36df$EmotRole  <- SF36df$Role_Emotional.y - SF36df$Role_Emotional.x
SF36df$Energy    <- SF36df$Energy.y - SF36df$Energy.x
SF36df$Emotional <- SF36df$Emotional.y - SF36df$Emotional.x
SF36df$Social    <- SF36df$Social.y - SF36df$Social.x
SF36df$Pain      <- SF36df$Pain.y - SF36df$Pain.x
SF36df$GenH      <- SF36df$General_Health.y - SF36df$General_Health.x

df        <- SF36df
changeVal <- SF36df$Pain
preVal    <- SF36df$Pain.x
Group     <- SF36df$Group.x

model <- Anova(lm(changeVal ~ Group + preVal, data = df, type="II"))

source("AncTable.R")
anc_Table <- ancova_Table(df, changeVal, preVal, Group)

```
## ASIA_SCI

```{r ASIA_SCI, echo=FALSE, message=FALSE, warning=FALSE}

ASIA <- read_excel("ASIA.xlsx")
#view(ASIA)
RAND <- RAND[c(1:11)]



pre  <- subset(ASIA, PrePost %like% "1")

p1 <- pre %>% filter(Group %like% "1")
tableC <-get_summary_stats(p1, show = c("min", "max","median", "iqr", "mean", "sd"))

df <- data.frame(matrix(ncol = 5, nrow = 0))

SF36df <- full_join(pre, post, by = "ID")
SF36df$Phys      <- SF36df$Physical.y - SF36df$Physical.x
SF36df$PhysRole  <- SF36df$Role_Physical.y - SF36df$Role_Physical.x
SF36df$EmotRole  <- SF36df$Role_Emotional.y - SF36df$Role_Emotional.x
SF36df$Energy    <- SF36df$Energy.y - SF36df$Energy.x
SF36df$Emotional <- SF36df$Emotional.y - SF36df$Emotional.x
SF36df$Social    <- SF36df$Social.y - SF36df$Social.x
SF36df$Pain      <- SF36df$Pain.y - SF36df$Pain.x
SF36df$GenH      <- SF36df$General_Health.y - SF36df$General_Health.x

df        <- SF36df
name      <- "GenH"
changeVal <- SF36df$GenH
preVal    <- SF36df$General_Health.x
Group     <- SF36df$Group.x

model <- Anova(lm(changeVal ~ Group + preVal, data = df, type="II"))

source("AncTable.R")
anc_Table <- ancova_Table(df, changeVal, preVal, Group, name)

df <- bind_rows(anc_Table[[2]])

```

## FIM_FAM

```{r FIM_FAM, echo=FALSE, message=FALSE, warning=FALSE}

FIM_FAM <- read_excel("FIM_FAM.xlsx")
#view(FIM_FAM)

pre  <- subset(FIM_FAM, PrePost %like% "1")
post <- subset(FIM_FAM, PrePost %like% "2")

df <- full_join(pre, post, by = "ID")
df$FIM_Motor     <- df$FIM_Motor.y    - df$FIM_Motor.x
df$FIM_COG       <- df$FIM_COG.y      - df$FIM_COG.x
df$FF_Selfcare   <- df$FF_Selfcare.y  - df$FF_Selfcare.x
df$FF_BladBowel  <- df$FF_BladBowel.y - df$FF_BladBowel.x
df$FF_Loco       <- df$FF_Loco.y      - df$FF_Loco.x
df$FF_Comm       <- df$FF_Comm.y      - df$FF_Comm.x
df$FF_PsycSoc    <- df$FF_PsycSoc.y   - df$FF_PsycSoc.x
df$FF_Think      <- df$FF_Think.y     - df$FF_Think.x


changeVal <- df$FF_Loco
name      <-   "FF_Loco"
preVal    <- df$FF_Loco.x
Group     <- df$Group.x

model <- Anova(lm(changeVal ~ Group + preVal, data = df, type="II"))

source("AncTable.R")
anc_Table <- ancova_Table(df, changeVal, preVal, Group, name)

FIM_FAM$PrePost <- as.factor(FIM_FAM$PrePost)

model <-  lmer(FF_Think ~  Group * PrePost + (1|ID), data=FIM_FAM, REML=T, control = lmerControl(optimizer ="Nelder_Mead"))
source("Lmer_Model_Table.R")
lmer <- Lmer_Model_Plot(FIM_FAM, FIM_FAM$FF_Think,  model)
lmer
```


## SSSMQ

```{r SSSMQ, echo=FALSE, message=FALSE, warning=FALSE}

SSSMQ <- read_excel("SSSMQ.xlsx")
#view(SSSMQ)

pre  <- subset(SSSMQ, PrePost %like% "1")
post <- subset(SSSMQ, PrePost %like% "2")

p1 <- post %>% filter(Group %like% "1")
tableC <-get_summary_stats(p1, show = c("min", "max","median", "iqr", "mean", "sd"))

df <- full_join(pre, post, by = "ID")
df$Ongoing_spinal_Pain     <- df$Ongoing_spinal_Pain.y    - df$Ongoing_spinal_Pain.x

df$Days_Neck_Pain_Month       <- df$Days_Neck_Pain_Month.y      - df$Days_Neck_Pain_Month.x
df$Days_UB_Pain_Month   <- df$Days_UB_Pain_Month.y  - df$Days_UB_Pain_Month.x
df$Days_MB_Pain_Month  <- df$Days_MB_Pain_Month.y - df$Days_MB_Pain_Month.x
df$Days_LB_Pain_Month       <- df$Days_LB_Pain_Month.y      - df$Days_LB_Pain_Month.x
df$Days_Butt_Pain_Month       <- df$Days_Butt_Pain_Month.y      - df$Days_Butt_Pain_Month.x

df$Hours_Neck_Pain_Per_Episode    <- df$Hours_Neck_Pain_Per_Episode.y   - df$Hours_Neck_Pain_Per_Episode.x
df$Hours_UB_Pain_Per_Episode      <- df$Hours_UB_Pain_Per_Episode.y     - df$Hours_UB_Pain_Per_Episode.x
df$Hours_MB_Pain_Per_Episode      <- df$Hours_MB_Pain_Per_Episode.y     - df$Hours_MB_Pain_Per_Episode.x
df$Hours_LB_Pain_Per_Episode      <- df$Hours_LB_Pain_Per_Episode.y     - df$Hours_LB_Pain_Per_Episode.x
df$Hours_Butt_Pain_Per_Episode      <- dfHours_Butt_Pain_Per_Episode.y     - df$Hours_Butt_Pain_Per_Episode.x

df$Consec_Days_Neck_Pain_Month    <- df$Consec_Days_Neck_Pain_Month.y   - df$Consec_Days_Neck_Pain_Month.x
df$Consec_DaysUB_Pain_Month    <- df$Consec_DaysUB_Pain_Month.y   - df$Consec_DaysUB_Pain_Month.x
df$Consec_DaysMB_Pain_Month    <- df$Consec_DaysMB_Pain_Month.y   - df$Consec_DaysMB_Pain_Month.x
df$Consec_DaysLB_Pain_Month    <- df$Consec_DaysLB_Pain_Month.y   - df$Consec_DaysLB_Pain_Month.x
df$Consec__Butt_Pain_Month    <- df$Consec__Butt_Pain_Month.y   - df$Consec__Butt_Pain_Month.x

df$Hache_freq    <- df$Hache_freq.y   - df$Hache_freq.x

df$Ave_pain_intensity_week    <- df$Ave_pain_intensity_week.y   - df$Ave_pain_intensity_week.x
df$Ave_pain_bearability_week    <- df$Ave_pain_bearability_week.y   - df$Ave_pain_bearability_week.x
df$Pain_intensity_today    <- df$Pain_intensity_today.y   - df$Pain_intensity_today.x
df$Pain_bearability_today    <- df$Pain_bearability_today.y   - df$Pain_bearability_today.x

changeVal <- df$Pain_bearability_today
preVal    <- df$Pain_bearability_today.x
Group     <- df$Group.x

model <- Anova(lm(changeVal ~ Group + preVal, data = df, type="II"))

source("AncTable.R")
anc_Table <- ancova_Table(df, changeVal, preVal, Group)
anc_Table


# difference bw Pre groups
K_test_Pres <-  kruskal.test(Ave_pain_bearability_week ~ Group, data = subset(SSSMQ, PrePost %like% "1"))
preDiff <- subset(SSSMQ, PrePost %like% "1") %>% group_by(Group) %>%
  dplyr::summarise(Medians = median(Ave_pain_bearability_week, na.rm = T), Mean = mean(Ave_pain_bearability_week, na.rm = T), SD = sd(Ave_pain_bearability_week, na.rm = T))
postDiff <- subset(SSSMQ, PrePost %like% "2") %>% group_by(Group) %>%
  dplyr::summarise(Medians = median(Ave_pain_bearability_week, na.rm = T), Mean = mean(Ave_pain_bearability_week, na.rm = T), SD = sd(Ave_pain_bearability_week, na.rm = T))


model <-  lmer(Ave_pain_bearability_week ~  Group * PrePost + (1|ID), data=SSSMQ, REML=T, control = lmerControl(optimizer ="Nelder_Mead"))
source("Lmer_Model_Table.R")
lmer <- Lmer_Model_Plot(SSSMQ, SSSMQ$Ave_pain_bearability_week,  model)

# Plot bearability
preDiff$PrePost <- 1
postDiff$PrePost <- 2

bearDF <- rbind(preDiff, postDiff)
bearDF$Group <- as.numeric(bearDF$Group)
bearDF$Group[bearDF$Group == 1] <- "Chiro"
bearDF$Group[bearDF$Group == 2] <- "Control"
save(bearDF, file = "bearDF.Rda")

bearDF$PrePost <- as.factor(bearDF$PrePost)
bearDF$Group <- as.factor(bearDF$Group)


bear <- ggplot(data=bearDF, aes(x=PrePost, y=Mean, group=Group))+
  geom_line( aes(linetype=Group ), color="royalblue4", linewidth=2, show.legend = F) +
  geom_errorbar(aes(ymin=Mean-SD, ymax=Mean+SD), color="royalblue4", width=.1, alpha=.5)+
  geom_point(aes(shape=Group), color="royalblue4", size = 3)+
  labs(title="Weekly pain bearability",x="", y="") +
  theme_classic() +
  theme(axis.text.x = element_text(size = 14),
        axis.text.y = element_text(size = 14), axis.title.y = element_text(size = 14),
        legend.title = element_blank(), legend.position = "bottom")+ 
  scale_x_discrete(limits=c("1","2"), labels=c("Pre", "Post"))

ggsave("bear.png", width = 15, height = 10, units = "cm")

```